# site settings
title: Соблюдение поста в исламе в месяце Рамадан 
subtitle: by HTML5 UP
email: test@gmail.com
description: Согласно Шариату, пост в месяце рамазан – обязанность (фарз).    Доказательство этому – Коран и сунна
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Nashville
state: TN
zip_code: 55555
country: 
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
